### ISSUE TITLE
Froze in E2EE modpack

### ISSUE THREAD

**Issue by Margatroidu** [kappa-maintainer/Sound-Physics#12]
I installed this mod in the E2EE modpack and the game freezes when I play it. I can't figure out what's causing this

[debug.log](https://github.com/user-attachments/files/18272195/debug.log)
[latest.log](https://github.com/user-attachments/files/18272196/latest.log)
https://mclo.gs/fVLWR7i

**Comment by kappa-maintainer** [comment]
1. Try to disable it and see if it crash
2. Try switching to Java 21 instead of Java 22
3. Try switching to Forge instead of Cleanroom
4. To be honest, please make sure it was SoundPhysics' fault before opening an issue

**Comment by Margatroidu** [comment]
I can already tell you that without it, there are no froze

**Comment by kappa-maintainer** [comment]
It freezes in any world upon entering game world?
If so, that sounds like a mod conflict, please follow the instructions:

1. Only enable those client only mods and see if it crashes, if so bisect through it
2. If it runs, disable all client only mods and enable content mods by series i.e. TE and all addons, Forestry and all addons
3. Don't disable optimization mods since iirc they compats

**Comment by Margatroidu** [comment]
> It freezes in any world upon entering game world? If so, that sounds like a mod conflict, please follow the instructions:
Freezing occurs after some time in the game, not immediately after entering the world

Now I will try to do as you said and tell you how it turned out.

**Comment by Margatroidu** [comment]
I'm playing on Forge right now and no freezing is happening. There must be some problem with Cleanroom

**Comment by Margatroidu** [comment]
I see what the problem is. Sound physics works fine in other worlds. Most likely my survival world is corrupted. Neither Cleanroom nor any other mods have anything to do with it
